# Generated by Django 4.2.5 on 2023-10-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-01 15:24:54.685574",
                max_length=156,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="salary",
            field=models.IntegerField(null=True),
        ),
    ]
