# Generated by Django 4.2.5 on 2023-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0002_alter_position_name_alter_staffuser_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-01 15:25:39.859076",
                max_length=156,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="fire_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="last_salary_review",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="retirement_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
