# Generated by Django 4.2.5 on 2023-10-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0005_company_owner_alter_position_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="foundation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-02 05:57:07.934817",
                max_length=156,
                unique=True,
            ),
        ),
    ]
