# Generated by Django 4.2.5 on 2023-10-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0007_company_country_registry_alter_position_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffuser",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_users",
                to="staff_app.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-02 07:35:37.963486",
                max_length=156,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="staff_app.department",
            ),
        ),
    ]
