# Generated by Django 4.2.5 on 2023-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0008_staffuser_company_alter_position_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffuser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="department",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="fire_date",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="last_salary_review",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="office",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="position",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="reporting_to",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="retirement_date",
        ),
        migrations.RemoveField(
            model_name="staffuser",
            name="salary",
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-02 08:40:58.601669",
                max_length=156,
                unique=True,
            ),
        ),
    ]
