# Generated by Django 4.2.5 on 2023-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0011_remove_department_owner_alter_position_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="company",
            field=models.ManyToManyField(
                related_name="company_offices", to="staff_app.company"
            ),
        ),
        migrations.AddField(
            model_name="office",
            name="department",
            field=models.ManyToManyField(
                related_name="department_offices", to="staff_app.company"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-03 10:00:04.713064",
                max_length=156,
                unique=True,
            ),
        ),
    ]
