# Generated by Django 4.2.5 on 2023-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0011_remove_department_owner_alter_position_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=156),
        ),
    ]
