# Generated by Django 4.2.5 on 2023-10-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0011_remove_department_owner_alter_position_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_comoffices",
                to="staff_app.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="office",
            name="department",
            field=models.ManyToManyField(
                related_name="department_offices", to="staff_app.company"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-03 08:33:54.376004",
                max_length=156,
                unique=True,
            ),
        ),
    ]
