# Generated by Django 4.2.5 on 2023-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0012_office_company_office_department_alter_position_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="office",
            name="company",
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                default="Unnamed position 2023-10-03 08:37:46.286626",
                max_length=156,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="office",
            name="company",
            field=models.ManyToManyField(
                related_name="company_comoffices", to="staff_app.company"
            ),
        ),
    ]
