# Generated by Django 4.2.5 on 2023-10-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0012_alter_position_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
