# Generated by Django 4.2.5 on 2023-10-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0013_position_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="staff_app.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=156, unique=True),
        ),
    ]
