# Generated by Django 4.2.5 on 2023-10-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0013_alter_position_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="department",
            field=models.ManyToManyField(
                related_name="department_offices", to="staff_app.department"
            ),
        ),
    ]
