# Generated by Django 4.2.5 on 2023-10-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0014_alter_office_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
