# Generated by Django 4.2.5 on 2023-10-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0015_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_logos"
            ),
        ),
    ]
