# Generated by Django 4.2.5 on 2023-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0017_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffuser",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile/logos"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/company/logos"
            ),
        ),
    ]
