# Generated by Django 4.2.5 on 2023-10-07 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0018_staffuser_logo_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="created_at_staff",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
