# Generated by Django 4.2.5 on 2023-10-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0019_department_created_at_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="department",
        ),
        migrations.AddField(
            model_name="position",
            name="department",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="staff_app.department",
            ),
            preserve_default=False,
        ),
    ]
