# Generated by Django 4.2.5 on 2023-10-08 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0020_remove_position_department_position_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="office",
            name="department",
        ),
    ]
