# Generated by Django 4.2.5 on 2023-10-08 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0021_remove_office_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="created_at_staff",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
