# Generated by Django 4.2.5 on 2023-10-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff_app", "0022_position_created_at_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="office",
            name="company",
        ),
        migrations.AddField(
            model_name="office",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_offices",
                to="staff_app.company",
            ),
            preserve_default=False,
        ),
    ]
